### ISSUE TITLE
Add video link?

### ISSUE THREAD

**Issue by batpigandme** [karthik/rstudio2019#2]
Would you be amenable to adding [a link to the video](https://resources.rstudio.com/rstudio-conf-2019/a-guide-to-modern-reproducible-data-science-with-r) of your talk at rstudio::conf? If so, I'm happy to PR (but won't be offended if you just want to DIY). 

Thanks again for this resource — 13/10 would recommend to all!

**Comment by karthik** [comment]
Hi Mara! Yes a PR would we great! 🙏
